# -*- coding: utf-8 -*-
"""Thyroid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APKMSgGY3MUIVs6Nx_-84w0qkZ-GKIaO
"""

!unzip thyroid+disease.zip

import pandas as pd

import matplotlib.pyplot as plt
import csv

columns = ["Class", "a", "g" ,"e" ,"n" ,"t"]

# Read the data from allypo.data
with open('new-thyroid.data', 'r') as infile, open('data.csv', 'w', newline='') as outfile:
    writer = csv.writer(outfile)
    writer.writerow(columns)  # Write the headers to the CSV file

    for line in infile:
        data = line.strip().split(',')
        writer.writerow(data)

df = pd.read_csv('data.csv')
df

df.fillna(df.mean(numeric_only=True), inplace=True)

X = df.drop('Class', axis=1)
y = df['Class']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4,random_state=42)

# Manually calculate the accuracy
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score

# Initialize and train the model
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
correct_predictions = (y_pred == y_test).sum()
total_predictions = len(y_test)
accuracy = correct_predictions / total_predictions

print(f'Accuracy: {accuracy * 100:.2f}%')

